version: '3.5'

services:
  redis-service:
    container_name: spotlive-local
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    ports:
      - 6374:6379
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    container_name: setanta-local
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    redis: